enum RouteNames {
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	DASHBOARD = 'DASHBOARD',
	MANAGEMENT_WALLETS = 'MANAGEMENT_WALLETS',
	CREATE_WALLETS = 'CREATE_WALLETS',
	EDIT_WALLETS = 'EDIT_WALLETS',
	MANAGEMENT_CATEGORY = 'MANAGEMENT_CATEGORY',
	CREATE_CATEGORY = 'CREATE_CATEGORY',
	EDIT_CATEGORY = 'EDIT_CATEGORY',
	NOTES = 'NOTES',
	CREATE_NOTE = 'CREATE_NOTE',
	DETAIL_NOTE = 'DETAIL_NOTE',
	NOTE_ITEMS = 'NOTE_ITEMS',
	CREATE_NOTE_ITEMS = 'CREATE_NOTE_ITEMS',
	EDIT_NOTE_ITEMS = 'EDIT_NOTE_ITEMS',
	MY_PROFILE = 'MY_PROFILE',
}

export default RouteNames;
