enum RouteNames {
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	DASHBOARD = 'DASHBOARD',
	MANAGEMENT_WALLETS = 'MANAGEMENT_WALLETS',
	CREATE_WALLETS = 'CREATE_WALLETS',
	EDIT_WALLETS = 'EDIT_WALLETS',
	MANAGEMENT_CATEGORY = 'MANAGEMENT_CATEGORY',
	NOTES = 'NOTES',
}

export default RouteNames;
